-- Add SEO and Branding settings keys if they don't exist
INSERT INTO settings (key, value) VALUES
('site_title', 'Gold X Usdt'),
('site_tagline', 'The Gold Standard of Digital Wealth'),
('seo_description', 'Experience the future of wealth generation with Gold X Usdt. 10% monthly ROI, secure blockchain infrastructure, and a powerful multi-level referral system.'),
('seo_keywords', 'gold usdt, crypto investment, passive income, high roi, secure wallet, usdt mining, wealth generation'),
('og_title', 'Gold X Usdt - Premium Crypto Investment Platform'),
('og_description', '10% monthly ROI, secure blockchain infrastructure, and a powerful multi-level referral system.'),
('og_image', ''),
('twitter_card', 'summary_large_image'),
('robots_txt', 'User-agent: *\nAllow: /\nDisallow: /admin/\nDisallow: /dashboard/'),
('primary_color', '#D4AF37'),
('secondary_color', '#1A1A1A'),
('accent_color', '#FFD700'),
('font_family', 'Inter, system-ui, Avenir, Helvetica, Arial, sans-serif'),
('logo_header_url', ''),
('logo_footer_url', ''),
('favicon_url', ''),
('contact_email', 'support@goldxusdt.com'),
('contact_phone', ''),
('contact_address', ''),
('social_facebook', ''),
('social_twitter', ''),
('social_instagram', ''),
('social_telegram', ''),
('analytics_code', ''),
('header_scripts', ''),
('footer_scripts', '')
ON CONFLICT (key) DO NOTHING;
